---
title: "Tidytuesday_Hockey Goals"
author: "LeiHe"
date: "12/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Get data here
```{r}
getwd()
library(tidyverse) 
# tuesdata <- tidytuesdayR::tt_load('2020-03-03')
tuesdata <- read_rds("data/hockey_goals_2020_0303.rds")
names(tuesdata)
game_goals <- tuesdata$game_goals
game_goals %>% glimpse()
```

#### summerise the  frequence of top10 player in game_goals 
```{r}
game_goals %>% 
  count(player) %>% 
  arrange(desc(n)) %>% 
  top_n(10) %>% 
  ggplot(aes(x = reorder(player, n), y = n, fill = player)) + 
  geom_col() + coord_flip() + theme(legend.position = "none")
```
#### calculate shots per goal for each player
```{r}
game_goals %>% 
  select(player, shots, goals) %>% 
  group_by(player) %>% 
  summarise(
    total_goals = sum(goals),
    total_shots = sum(shots)
  ) %>% 
  mutate(
    shots_per_goals = total_shots/total_goals,
    levels = cut(shots_per_goals, 3, labels = 1:3)
    ) %>% 
  arrange(desc(total_goals)) %>% 
  top_n(20) %>% 
  ggplot(aes(x = total_shots, y = total_goals)) +
  geom_point(aes(color = player, size = levels)) +
  geom_smooth() +
  theme_bw() +
  theme(
    legend.position = "none"
  )
  
```

```{r}
dat <- game_goals %>% 
  select(goals, player, season, game_num, age, team, opp, location, assists, shots) 
```

```{r}
dat %>% 
  select(assists, shots, goals) %>% 
  na.exclude() %>% 
  gather(key = "key", value = "value", -goals) %>% 
  ggplot(aes(x = value, y = goals, color = key)) +
  geom_jitter(alpha = .1) +
  geom_smooth() +
  facet_wrap(~key, scales = "free")
```
#### make linear model for bin of total_goals within each players
```{r}
model_dat <- dat %>% 
  group_by(player) %>% 
  mutate(
    total_goals = sum(goals)
  ) %>% 
  ungroup() %>% 
  mutate(rank = dense_rank(-total_goals)) %>% 
  mutate(rank = floor(rank/10) + 1) %>% 
  arrange(desc(total_goals)) %>% 
  separate(age, into = c("year", "day")) %>% 
  mutate(
    age = as.integer(year) + as.numeric(day)/365
  ) %>% 
  select(-year, -day, -season, -total_goals) %>% 
  group_by(rank) %>% 
  mutate(sd_game_num = (game_num - mean(game_num))/sd(game_num)) %>% 
    ungroup() %>% 
    select(-game_num, -player) %>% 
    select(rank, everything())

library(broom)

lapply(split(model_dat, model_dat$rank), function(x){
  linear_model = lm(goals~., data = x)
  broom::tidy(linear_model) %>% 
    filter(term != "rank")
  }
) %>% 
  do.call(rbind, .) %>% 
  rownames_to_column(var = "rank") %>% 
  mutate(
    rank = str_remove_all(rank, "\\.\\d+")
  ) %>% 
  filter(p.value <= .05) %>% 
  ggplot(aes(x = reorder(term, estimate), y = estimate, fill = rank)) +
  geom_col() + coord_flip() +
  facet_wrap(~rank, scales = "free")
```

